import os

from dotenv import load_dotenv

load_dotenv()


def _get_required_env_var(var_name):
    env_var = os.getenv(var_name)
    if not env_var:
        raise RuntimeError(f'Environment variable {var_name} is required but was not provided.')
    return env_var


class Config:
    DEBUG = os.getenv('DEBUG', 'False').lower() in ['true', '1']

    # Token generated by BotFather
    TG_BOT_TOKEN = _get_required_env_var('TG_BOT_TOKEN')

    # Index in where the media will be indexed in ElasticSearch
    ES_INDEX_NAME = os.getenv('ES_INDEX_NAME', 'telegram-saved-media-bot')
